exp_name: cross_depth_blur_lessblurv2_gopro # <experiment name and  name of directory to save the experimental results and logs>

train:
  train_inp: /home/ziyao/ArkitData/upsampling/Validation/blurred # <path to the directory of blur input images for training>
  train_gt: /home/ziyao/ArkitData/upsampling/Validation/wide # <path to the directory of rgb ground truth images for training>
  train_dep: /home/ziyao/ArkitData/upsampling/Validation/lowres_depth # <path to the directory of depth input images for training>
  train_gt_dep: false
  valid_inp: /home/ziyao/ArkitData/upsampling/Validation/blurred # <path to the directory of blur input images for validation>
  valid_gt: /home/ziyao/ArkitData/upsampling/Validation/wide  # <path to the directory of rgb ground truth images for validation>
  valid_dep: /home/ziyao/ArkitData/upsampling/Validation/lowres_depth # <path to the directory of depth input images for validation>
  batch_size: 16
  patch_size: 256
  epoch: 200 
  lr: 5e-5
  num_workers: 0
  save_every: 20 # frequency of save the model
  prompt_tuning: false #if you want to freeze all the network and only training the adapter, set to true
  encoder_freezing: false # if you wan to freeze all the encoder,

test:
  test_inp: /media/HDD/ziyao/lessblurdataset/test/result_test_color_img # <path to the directory of blur input images for test>
  test_gt: /media/HDD/ziyao/lessblurdataset/test/result_test_gt # <path to the directory of rgb ground truth images for test>
  test_dep: /media/HDD/ziyao/lessblurdataset/test/result_test_depth_img # <path to the directory of depth input images for validation>
  num_workers: 0
  save: true

model:
  name: DepthStripformer
  pretrained: false # <path to the pretrained model>, not used if set false, p.s. each pretrained model has different keys(), e.g. resotormer's parameters are saved in 'params' while others are saved in pth.
  resume: false
  gpu_ids: false
  node: 1
  num_gpus: 2