exp_name: catrestormer #  <experiment name and  name of directory to save the experimental results and logs>
train:
  train_inp: /home/valsesia/Scripts/ARKitScenes/data/upsampling/upsampling/Training/wide # <path to the directory of blur input images for training>
  train_dep: /home/valsesia/Scripts/ARKitScenes/data/upsampling/upsampling/Training/lowres_depth # <path to the directory of depth input images for training>
  valid_inp: /home/valsesia/Scripts/ARKitScenes/data/upsampling/upsampling/Validation/small_set # <path to the directory of blur input images for validation>
  valid_gt: /home/valsesia/Scripts/ARKitScenes/data/upsampling/upsampling/Validation/wide   # <path to the directory of rgb ground truth images for validation>
  valid_dep: /home/valsesia/Scripts/ARKitScenes/data/upsampling/upsampling/Validation/lowres_depth # <path to the directory of depth input images for validation>
  batch_size: 3
  patch_size: 256
  epoch: 200
  lr: 1e-4
  num_workers: 0
  save_every: 10 # frequency of save the model
  prompt_tuning: false #if you want to freeze all the network and only training the adapter, set to true
  encoder_freezing: false # if you wan to freeze all the encoder,

test:
  test_inp: /home/valsesia/Scripts/ARKitScenes/data/upsampling/upsampling/Validation/small_set # <path to the directory of blur input images for test>
  test_gt: /home/valsesia/Scripts/ARKitScenes/data/upsampling/upsampling/Validation/wide # <path to the directory of rgb ground truth images for test>
  test_dep: /home/valsesia/Scripts/ARKitScenes/data/upsampling/upsampling/Validation/lowres_depth # <path to the directory of depth input images for validation>
  num_workers: 0
  save: true #if you need save the image

# for training
# model:
#   name: DepthRestormer
#   setting: false
#   pretrained: ""  # checkpoint location set false if is none
#   gpu_ids: false
#   num_gpus: 4  ### while test or demo please set num_gpu to 1
#   node: 1
#   resume: true #if you are continue training on a unfinished model
#   testing_from_dp: false
  
# for testing
model:
  name: CatRestormer
  setting: false
  pretrained: pretrainedModel/depthrestormer/deblur/catrestormer.pth # checkpoint location set false if is none
  gpu_ids: false
  num_gpus: 1  ### while test or demo please set num_gpu to 1
  node: 1
  resume: true #if you are continue training on a unfinished model
  testing_from_dp: false # discard module prefix when loading checkpoint due to training with dataparallel
  
